import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import { aws_glue as glue } from 'aws-cdk-lib';
import * as iam from 'aws-cdk-lib/aws-iam';

export class AwsDataInfraStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // Create Insurance Data Bucket, autogenerated bucket name
    // s3://awsdatainfrastack-databucketXXX/
    const dataBucket = new s3.Bucket(this, 'DataBucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
    });
    
    // Upload test data to S3 bucket
    new s3deploy.BucketDeployment(this, 'DeployWebsite', {
      sources: [s3deploy.Source.asset('../01-Generate-Test-Data/CSV')],
      destinationBucket: dataBucket,
      destinationKeyPrefix: 'data'
    });

    // Define Glue Classifier include headers
    const cfnClassifier = new glue.CfnClassifier(this, 'MyCfnClassifier', {
      csvClassifier: {
        allowSingleColumn: false,
        containsHeader: 'PRESENT',
        delimiter: ',',
        //disableValueTrimming: false,
        //header: [''],
        name: 'import-csv-with-header',
        quoteSymbol: '"'
      }
    });

    // IAM Role for Glue that can access Insurance Data Bucket
    const glueRole = new iam.Role(this, 'AWSGlueServiceRole-insurance-data', {
      assumedBy: new iam.ServicePrincipal('glue.amazonaws.com'),
    });

    const gluePolicy = iam.ManagedPolicy.fromAwsManagedPolicyName("service-role/AWSGlueServiceRole");
    glueRole.addManagedPolicy(gluePolicy);
    dataBucket.grantRead(glueRole);

    // CfnCrawler = L1 construct in CDK
    // https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_glue.CfnCrawler.html
    new glue.CfnCrawler(this, 'insurance_data_crawler', {
      databaseName: 'insurance_database',
      role: glueRole.roleArn,
      targets: {
        s3Targets: [{ path: dataBucket.bucketName + "/data/" }]
      },
      classifiers: ['import-csv-with-header']
    });

  }
}
